export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';
export const GET_ID_CATEGORY = 'GET_ID_CATEGORY';
